site_name: Yusux 的笔记本
site_url: https://note.yusux.xyz
site_description: 杂事杂录
repo_name: Yusux/note
repo_url: https://github.com/Yusux/note
edit_uri: tree/master/docs
copyright: Copyright &copy; 2024 Yusux

theme: 
  name: material
  language: 'zh'
  favicon: assets/img/favicon-32x32.png
  icon: 
    logo: material/notebook-outline
  custom_dir: docs/overrides
  features:
    - content.code.annotate
    - content.code.copy
    - navigation.tracking
    - navigation.tabs
    - navigation.indexes
    - navigation.top
  font: false
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

markdown_extensions:
  - toc:
      permalink: true
      toc_depth: 4
  - meta
  - def_list
  - attr_list
  - md_in_html
  - sane_lists
  - admonition
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.snippets
  - pymdownx.magiclink
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.arithmatex:
      generic: true

extra:
  social:
    - icon: octicons/mark-github-16
      link: https://github.com/Yusux
    - icon: octicons/home-16
      link: https://yusux.xyz

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/contrib/auto-render.min.js
  - assets/js/katex.js

extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/lxgw-wenkai-screen-webfont/1.7.0/lxgwwenkaiscreen.min.css
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.9/katex.min.css
  - https://cdn.jsdelivr.net/npm/jetbrains-mono@1.0.6/css/jetbrains-mono.min.css
  - assets/css/card.css
  - assets/css/moegirl.css
  - assets/css/page.css
  - assets/css/counter.css
  - assets/css/tasklist.css

plugins:
  - search
  - git-revision-date-localized:
      type: datetime
      timezone: Asia/Shanghai
      locale: zh
      enable_creation_date: true
      exclude:
        - index.md
  - statistics:
      page_check_metadata: totalwd
  - mathenv:
      tikzpicture:
        enable: true
        cachefile: true

nav:
  - Home:
    - index.md
    - friends.md
  - Computer Science:
    - CS/index.md
    - 编译原理:
      - CS/Compilers/index.md
      - 概述: CS/Compilers/ch1.md
      - 词法分析: CS/Compilers/ch2.md
      - 语法分析:
        - CS/Compilers/ch3/index.md
        - CFG 及语法分析概述: CS/Compilers/ch3/ch3-1.md
        - 自顶向下分析: CS/Compilers/ch3/ch3-2.md
        - 自底向上分析: CS/Compilers/ch3/ch3-3.md
        - 语法分析器与小结: CS/Compilers/ch3/ch3-4.md
      - 抽象语法: CS/Compilers/ch4.md
      - 语义分析: CS/Compilers/ch5.md
      - 活动记录: CS/Compilers/ch6.md
      - 中间代码生成: CS/Compilers/ch7.md
      - 基本块和 Traces: CS/Compilers/ch8.md
      - 指令选择: CS/Compilers/ch9.md