site_name: Rorin 的笔记本
site_url: https://note.rorin.cc
site_description: 杂事杂录
repo_name: Yusux/note
repo_url: https://github.com/Yusux/note
edit_uri: tree/master/docs
copyright: Copyright &copy; 2024-2025 Rorin

theme: 
  name: material
  language: 'zh'
  favicon: https://cdn.jsdelivr.net/gh/Yusux/note/docs/assets/img/favicon-32x32.png
  icon: 
    logo: material/notebook-outline
  custom_dir: docs/overrides
  features:
    - content.code.annotate
    - content.code.copy
    - navigation.tracking
    - navigation.tabs
    - navigation.indexes
    - navigation.top
  font: false
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

markdown_extensions:
  - toc:
      permalink: true
      toc_depth: 4
  - meta
  - def_list
  - attr_list
  - md_in_html
  - sane_lists
  - admonition
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.snippets
  - pymdownx.magiclink
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.arithmatex:
      generic: true

extra:
  social:
    - icon: octicons/mark-github-16
      link: https://github.com/Yusux
    - icon: octicons/home-16
      link: https://rorin.cc

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/contrib/auto-render.min.js
  - https://cdn.jsdelivr.net/gh/Yusux/note/docs/assets/js/katex.js

extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/lxgw-wenkai-screen-webfont/1.7.0/lxgwwenkaiscreen.min.css
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.9/katex.min.css
  - https://cdn.jsdelivr.net/npm/jetbrains-mono@1.0.6/css/jetbrains-mono.min.css
  - https://cdn.jsdelivr.net/gh/Yusux/note/docs/assets/css/card.css
  - https://cdn.jsdelivr.net/gh/Yusux/note/docs/assets/css/moegirl.css
  - https://cdn.jsdelivr.net/gh/Yusux/note/docs/assets/css/page.css
  - https://cdn.jsdelivr.net/gh/Yusux/note/docs/assets/css/counter.css
  - https://cdn.jsdelivr.net/gh/Yusux/note/docs/assets/css/tasklist.css

plugins:
  - search
  - git-revision-date-localized:
      type: datetime
      timezone: Asia/Shanghai
      locale: zh
      enable_creation_date: true
      exclude:
        - index.md
  - statistics:
      page_check_metadata: totalwd
  - mathenv:
      tikzpicture:
        enable: true
        cachefile: true

nav:
  - 根:
    - index.md
    - friends.md
  - 计算机科学:
    - cs/index.md
    - 编译原理:
      - cs/compilers/index.md
      - 概述: cs/compilers/ch1.md
      - 词法分析: cs/compilers/ch2.md
      - 语法分析:
        - cs/compilers/ch3/index.md
        - CFG 及语法分析概述: cs/compilers/ch3/ch3-1.md
        - 自顶向下分析: cs/compilers/ch3/ch3-2.md
        - 自底向上分析: cs/compilers/ch3/ch3-3.md
        - 语法分析器与小结: cs/compilers/ch3/ch3-4.md
      - 抽象语法: cs/compilers/ch4.md
      - 语义分析: cs/compilers/ch5.md
      - 活动记录: cs/compilers/ch6.md
      - 中间代码生成: cs/compilers/ch7.md
      - 基本块和 Traces: cs/compilers/ch8.md
      - 指令选择: cs/compilers/ch9.md
      - 活跃变量分析: cs/compilers/ch10.md
      - 寄存器分配: cs/compilers/ch11.md
      - 垃圾回收: cs/compilers/ch13.md
      - 面向对象语言: cs/compilers/ch14.md
      - 循环优化: cs/compilers/ch18.md
  - 随记:
    - note/index.md
    - 具身智能:
      - note/robotics/index.md
      - RoboCasa: note/robotics/RoboCasa.md
      - Open X-Embodiment: note/robotics/Open-X-Embodiment.md
      - HumanPlus: note/robotics/HumanPlus.md
    - 计算机视觉:
      - note/cv/index.md
      - MASt3R: note/cv/MASt3R.md
      - CAT3D: note/cv/CAT3D.md
    - 大语言模型:
      - note/llm/index.md
      - MCTSr: note/llm/MCTSr.md