name: ci 
on:
  push:
    branches:
      - master 
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV
      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - run: pip install mkdocs-material
      - name: Install MkDocs Plugins
        run: |
          pip install mkdocs-git-revision-date-localized-plugin mkdocs-material-extensions
          git clone https://github.com/Yusux/mkdocs-mathenv-plugin.git
          pip install -e mkdocs-mathenv-plugin
          git clone https://github.com/Yusux/mkdocs-statistics-plugin.git
          pip install -e mkdocs-statistics-plugin
      - name: Install LaTex Dependencies
        run: |
          sudo apt-get update
          sudo DEBIAN_FRONTEND=noninteractive apt-get install -y texlive-xetex texlive-fonts-recommended texlive-fonts-extra dvisvgm mupdf-tools
      - run: mkdocs gh-deploy --force